### PR TITLE
RC 0.3.0

### LINKED ISSUE #66: Uh-60M turrets occasionally delete players model
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

([Server RPT](https://gist.github.com/SirGhosty22/15fa0c411b34f8cf9c6c490c650b09f4)

# Bug Report

## **Description:**

When dismounting from UH-60M turrets, players get "Deleted" for lack of a better word, they go invisable and cannot interact with the world until respawn

### **Expected Behavior**

Players dismount with a funtioning body and the ability to be seen

### Steps to Reproduce the Issue

1. Get in UH-60m turret
2. Dismount

### **Video**

- [Video showing what happened](https://www.youtube.com/watch?v=tYTMiWNxO58&feature=youtu.be )

### **Additional context**

N/A

### PR DESCRIPTION
**Pull request by ampersand38**
Admin:
- .editorconfig indent size from 4 to 2
- minor version from 0.2.1 to 0.3.0
- stringtables in most components

Cockpit:
- stage 1 of pilotCamera-based flir for all models except UH-60M
- copilot head limit matches pilot
- New HMD features including waypoint info, metric units, declutter modes

Animation Sources;
- `GunnerSeats_Hide`
- `Minigun_Mount_L_hide` ammo box, belt, armature
- `Minigun_Mount_R_hide` ammo box, belt, armature
- `Minigun_L_hide`
- `Minigun_R_hide`

Model related:
- Front wheel dampers no longer collapse
- Cabin doors closed and open state don't clip or leave gaps
- Hoist hook no longer slingloadable
- Floor FFV seats individually accessible

Vehicle-in-vehicle:
- HH-60 and MH-60M viv space btween gunner seats and ERFS, blocks and is blocked by passengers in the floor FFV seats, door seats not affected

Added FD RALT Toggle keybind, request your favourite here https://github.com/Project-Hatchet/public_h-60/issues/71

Close #66, #46, #44, #22, #5

Use model from https://github.com/Project-Hatchet/private_h-60/pull/3

### CODE REVIEW

**Review by YannikH — CHANGES_REQUESTED** [review]
Overall it's looking great, but there's some issues I'm running in to

- Not a single variant has doorguns
- When the doorguns are removed, we should also hide the mounts and feed chutes at least
- MH-60S (Pylons) has the double M134 weapon from the DAP on the pilot
- I can't load anything in to the MEV version

**Comment by YannikH** [comment]
image
The LOD in the back doesn't have the door aligned properly

**Comment by ampersand38** [comment]
Outstanding issues:
- vtx_MH60S, vtx_MH60S_GAU21L doorguners no vxf, but vtx_MH60S_Pylons is fine
- doorgunner seats not hidden in view pilot and view cargo
- warning on entering UH60M pilot seat:
```
Warning Message: No entry 'bin\config.bin/RscInGameUI.'.
Warning Message: No entry '.idd'.
Warning Message: '/' is not a value
```

**Comment by YannikH** [comment]
`Warning Message: No entry 'bin\config.bin/RscInGameUI.'.
Warning Message: No entry '.idd'.
Warning Message: '/' is not a value`

This one is on me I think, it's because the UH-60M has no pilotcamera UI.

I can just fix it for 0.3.1

**Review by YannikH — APPROVED** [review]

**Comment by ampersand38** [comment]
Close #69

**Pull request merged**
