### PR TITLE
HMD Improvements

### LINKED ISSUE #3: HMD Waypoint heading points to [0,0,0] when there is no waypoint

### LINKED ISSUE #10: Fix hover mode symbology
- [x] Remove the hover mode symbology from the PFD screen
- [x] Fix the Horizontal WP indicator on the HMD
- [x] Improve the style of the hover indicator on the HMD

### LINKED ISSUE #41: Add additional Information To HMD
**Is your feature request related to a problem? Please describe.**
The HMD baked into the blackhawks doesnt have as much funtionality as third party HMD mods

**Describe the solution you'd like**
Configurable options for the HMD, new features/funtionality.
See Screenshot with detailed layout

**Describe alternatives you've considered**
Bake in Kimis HMD mod

**Additional context**
image

### LINKED ISSUE #48: Add level indicators to PFD pitch ladder

### PR DESCRIPTION
**Pull request by YannikH**

### CODE REVIEW

**Comment by ampersand38** [comment]
Elements moving with FOV change:
- slip ball
- wp arrow on heading tape
- triangle boresight

With WP set in FNS, Custom Waypoint overrides:
- wp arrow on heading tape 
- wp distance

With no wp set in FMS, these things point to map [0,0,0]:
- Top down LZ helper
- WP heading and travel time 

Other:
- Top down LZ helper doesn't seem to switch to imperial
- Was the altitude above sea level left out on purpose?

**Comment by YannikH** [comment]
Triangle boresight is actually the FLIR direction
FOV change on WP arrow and trianlge boresight can't be changed easily

Custom waypoint fixed (now all HUD elements point to the custom waypoint when one is present, waypoint name is MAP WPT)

image

LZ Helper now switches to imperial

ASL(MSL) altitude indicator added

**Comment by ampersand38** [comment]
Looks really awesome! It's unfortunate that slip ball and heading tape arrow move on zoom, but at least there's no real reason to be looking at them while zoomed in.

**Review by ampersand38 — APPROVED** [review]

**Comment by ampersand38** [comment]
Potential tweaks that might be nice:
- make the Speed box the same level with the MSL altitude box
- Hide Q 0 C 0 in SFM

**Comment by ampersand38** [comment]
close #31

**Pull request merged**
