### PR TITLE
Feature/improve auto start

### PR DESCRIPTION
**Pull request by YannikH**
**When merged this pull request will:**
- Make a quick start feature that doesn't suck

### CODE REVIEW

**Comment by ampersand38** [comment]
Needs a rebase right? It's adding pylons all over again.

**Comment by FatLurch** [comment]
Currently, perSecond for the engine has an `exitWith` if the user has simple startup enabled. What is the intent of this?

When I remove this locally for testing, I'm able to get fuel burn working with simple startup.

Is there a consequence of this I haven't noticed?

**Comment by FatLurch** [comment]
#291 is built upon this and adds a Simple Shutdown

**Comment by YannikH** [comment]
Won't work after SFM+

**Pull request closed without merging**
