### PR TITLE
Pilot rescue

### PR DESCRIPTION
**Pull request by ampersand38**
**When merged this pull request will:**
- separate compartments for pilot and cabin
- add interaction to allow cabin pers to switch with pilot when pilot is gone, dead, unconcious, or ai
- https://www.youtube.com/watch?v=8TxBsRx7VII

### CODE REVIEW

**Review by YannikH — CHANGES_REQUESTED** [review]
Does this break all the interaction stuff as you switch?
And can we make this always work, not jsut when the pilot is dead, so crew chiefs can always move to the cockpit

**Comment by ampersand38** [comment]
Yeah a lot of our custom stuff will probably break with the switch, but it'll be good enough to do rtb or emergency land.
So right now we can forcibly kick the pilot out (and put in back), I don't think we want that while the pilot is in control, right?
I suppose I should make it check the copilot seat first. and go there if it's empty.

**Comment by YannikH** [comment]
We'd want it to just move to any empty seat in the cockpit, if there is no empty cockpit seat, I think we should not let them go in to the cockpit

**Comment by ampersand38** [comment]
Ah, i thought the idea was to have a fail safe if both pilots get unconscious.

**Comment by YannikH** [comment]
my idea with the compartment change was to allow copilots and crew chiefs to pull double duty, so a two manned helicopter can have one permanent pilot and one person who can do both copilot and crew chief duty

**Review by YannikH — APPROVED** [review]
Looks good

**Pull request merged**
