### PR TITLE
Garage customization textures and animations, Turn out, model fixes

### LINKED ISSUE #157: Model: Blue line showing in cabin for pilot or co-pilot of MH-60 and MH-60 DAP
# Model Error report 

## **Description:**

- When in either the pilot or co-pilot seat of an MH-60 or MH-60 DAP when looking back into the cabin a blue line can be seen running through roughly the middle of the cabin. This does not occur on other versions or from other seats.

### PR DESCRIPTION
**Pull request by ampersand38**
**When merged this pull request will:**
- Add Texture and Animation customization via Garage
- Add Turn Out for door and window gunners https://www.youtube.com/watch?v=4H-7rK-_Uqg, https://www.youtube.com/watch?v=xO6yVlIOjU0
- Fix SFM center of mass https://www.youtube.com/watch?v=IiNMQ0UCBDc
- Fix viewCargo model errors for cabin doors, pylons, gunner seats
- Close #157, #111, #164

### CODE REVIEW

**Comment by ampersand38** [comment]
Some animations aren't being set properly, like mh/hh fuel probes, fuel tank, hh60 flares.
Resolved with model update.

**Comment by ampersand38** [comment]
Will close #157

**Comment by ampersand38** [comment]
Tweaked minigun sights to center and added selections to hide sights #111 and hoist #164 
image
image
image
Tweaked SFM center of mass to be behind the rotor https://youtu.be/IiNMQ0UCBDc

**Comment by ampersand38** [comment]
Fixed pylon positions in viewCargo
image
image

**Comment by ampersand38** [comment]
Fixed Double Gunner Seats in ViewCargo https://youtu.be/39gG1ZZDDn0

**Comment by ampersand38** [comment]
Doorgunners turn out https://youtu.be/xO6yVlIOjU0

**Review by YannikH — APPROVED** [review]
Everything you do is perfect

**Comment by ampersand38** [comment]
re-done here https://github.com/Project-Hatchet/H-60/pull/236

**Pull request closed without merging**
