### PR TITLE
Fix ESIS on Get out/in

### LINKED ISSUE #269: Bug: ESIS Screen Disappears after getting back in the helicopter
When the aircraft is running and the pilot gets out then gets back in, the ESIS changes to a white screen. Turning the STBY INST switch off then on again reboots the ESIS properly.

### PR DESCRIPTION
**Pull request by FatLurch**
**When merged this pull request will:**
- Fixes #269 

The UH60_engine_fnc_setup is being called every time a player gets in the aircraft. 

I'm fearful this also means the eventHandler it adds is being stacked?

### CODE REVIEW

**Comment by ampersand38** [comment]
If you remove that, does ESIS still run on start up?

**Comment by FatLurch** [comment]
> If you remove that, does ESIS still run on start up?

Yes, it was working when I tested locally.

**Review by ampersand38 — APPROVED** [review]
Good fix for now. The engine stuff really needs to be unified.

**Comment by YannikH** [comment]
I'm not sure exactly why this works but yeah it still does, what the hell

**Comment by FatLurch** [comment]
> I'm not sure exactly why this works but yeah it still does, what the hell

Lmao, I tried it on a whim and that was my conclusion as well.

**Pull request merged**
